language: python
python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install --dev
  - curl -sL https://sentry.io/get-cli/ | bash
  - sentry-cli --version

services:
  - docker

script:
  - pipenv run pytest

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - REPO=datacite/viringo;
  - AUTO_DEPLOY=false;
  - if [ "${TRAVIS_TAG?}" ]; then
      docker build -f Dockerfile -t $REPO:$TRAVIS_TAG .;
      docker push $REPO:$TRAVIS_TAG;
      echo "Pushed to" $REPO:$TRAVIS_TAG;
      AUTO_DEPLOY=true;
    elif [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker build -f Dockerfile -t $REPO .;
      docker push $REPO;
      echo "Pushed to" $REPO;
      AUTO_DEPLOY=true;
    else
      docker build -f Dockerfile -t $REPO:$TRAVIS_BRANCH .;
      docker push $REPO:$TRAVIS_BRANCH;
      echo "Pushed to" $REPO:$TRAVIS_BRANCH;
    fi

  - if [ "$AUTO_DEPLOY" == "true" ]; then
      wget https://github.com/jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-amd64-v0.6.0.tar.gz;
      tar -xzvf dockerize-linux-amd64-v0.6.0.tar.gz;
      rm dockerize-linux-amd64-v0.6.0.tar.gz;
      export GIT_SHA=$(git rev-parse --short HEAD);
      export GIT_REVISION=$(git rev-parse HEAD);
      export GIT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1));

      git clone "https://${TRAVIS_SECURE_TOKEN}@github.com/datacite/mastino.git";
      ./dockerize -template vendor/docker/_viringo.auto.tfvars.tmpl:mastino/stage/services/oai/_viringo.auto.tfvars;

      sentry-cli releases new viringo:${GIT_TAG} --finalize --project viringo;

      if [ "${TRAVIS_TAG?}" ]; then
        ./dockerize -template vendor/docker/_viringo.auto.tfvars.tmpl:mastino/prod-eu-west/services/oai/_viringo.auto.tfvars;
        sentry-cli releases deploys viringo:${GIT_TAG} new -e production;
      else
        sentry-cli releases deploys viringo:${GIT_TAG} new -e stage;
      fi

      sentry-cli releases set-commits --auto viringo:${GIT_TAG};
      
      cd mastino;
      git remote;
      git config user.email ${DOCKER_EMAIL};
      git config user.name ${DOCKER_USERNAME};
      
      if [ "${TRAVIS_TAG?}" ]; then
        git add prod-eu-west/services/oai/_viringo.auto.tfvars;
        git commit -m "Adding viringo git variables for commit tagged ${TRAVIS_TAG?}";
        git push "https://${TRAVIS_SECURE_TOKEN}@github.com/datacite/mastino.git" master;
      else
        git add stage/services/oai/_viringo.auto.tfvars;
        git commit -m "Adding viringo git variables for latest commit";
        git push "https://${TRAVIS_SECURE_TOKEN}@github.com/datacite/mastino.git" master;
      fi
    fi

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
