language: python
python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv install

services:
  - docker

script:
  - pytest
  - ./vendor/travis/docker.sh

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
